In [29]:
import numpy as np
import torch
import random

x = {'hi': np.empty([5,2])}

x['hi'][0] = np.array([1,2])
x['hi'][1] = np.array([3,4])
x['hi'][2] = np.array([5,6])
x['hi'][3] = np.array([7,8])
x['hi'][4] = np.array([9,10])

indices = random.sample(range(5), 2)
print(indices)

print(torch.as_tensor(x['hi'][indices]))

[2, 4]
tensor([[ 5.,  6.],
        [ 9., 10.]], dtype=torch.float64)


In [4]:
import numpy as np
print(np.random.uniform(size=5))
np.where(np.random.uniform(size=5) < 0.8)

[0.70116938 0.39414073 0.72170246 0.44115421 0.30410546]


(array([0, 1, 3, 4]),)

In [5]:
import numpy as np
import torch
import random

x = {'hi': np.empty([10,2])}
x['hi'][0]
indices = np.random.randint(10,size = 3)
x['hi'][indices]
np.random.uniform(size=5)

np.random.randint(10, size=3)[0]

3