In [8]:
import numpy as np
import random
import torch

In [9]:
a = np.array([1,2,3])
b = np.matrix([[1],[2],[3]])
c = np.matrix([[1,4],[2,5],[3,6]])

c = np.array([[[[0], [1], [2], [3]]]])


print(c)

# print((a * (b+c)).sum())

[[[[0]
   [1]
   [2]
   [3]]]]


In [10]:
directions = np.array([
            [-1,0], #UP
            [0,-1], #LEFT
            [1,0], #DOWN
            [0,1] #RIGHT
        ])
print(directions[0])

[-1  0]


In [11]:
obstacles = np.zeros((2, 3))
for i in range(2):
    obstacles[ random.randrange(2) , random.randrange(3)] = 1
print(obstacles)

[[0. 0. 0.]
 [0. 1. 1.]]


In [12]:
c = np.array([[1,4],[2,3]])
print(c.shape)

(2, 2)


In [13]:
c_p = np.array([i for i in range(0,100,5)])/100
c_v = np.array([i for i in range(0,100,10)])/100
c = list(zip(c_p,c_v))

x = c[2][1]
print(c)
print(x)

[(0.0, 0.0), (0.05, 0.1), (0.1, 0.2), (0.15, 0.3), (0.2, 0.4), (0.25, 0.5), (0.3, 0.6), (0.35, 0.7), (0.4, 0.8), (0.45, 0.9)]
0.2


In [42]:
(1-1/6) - 1/6

#1/6 + 1/6 + 1/6 + 1/6 + 1/6

1 - 1/7

x = [random.uniform(0.1,0.9) for _ in range(4)]
print(x)

for i in range(0):
    print(i)

6**2

[0.7990227547685759, 0.875382084881917, 0.6017580978656027, 0.5926674161676724]


36