In [2]:
import numpy as np
import random

In [3]:
a = np.array([1,2,3])
b = np.matrix([[1],[2],[3]])
c = np.matrix([[1,4],[2,5],[3,6]])

c = np.array([[[[0], [1], [2], [3]]]])


print(c)

# print((a * (b+c)).sum())

[[[[0]
   [1]
   [2]
   [3]]]]


In [4]:
directions = np.array([
            [-1,0], #UP
            [0,-1], #LEFT
            [1,0], #DOWN
            [0,1] #RIGHT
        ])
print(directions[0])

[-1  0]


In [5]:
obstacles = np.zeros((2, 3))
for i in range(2):
    obstacles[ random.randrange(2) , random.randrange(3)] = 1
print(obstacles)

[[0. 0. 1.]
 [1. 0. 0.]]


In [6]:
c = np.array([[1,4],[2,3]])
print(c.shape)

(2, 2)


In [8]:
print(np.inf)

inf
