In [2]:
import numpy as np
import random
import torch
from collections import deque

In [3]:
a = np.array([1,2,3])
b = np.matrix([[1],[2],[3]])
c = np.matrix([[1,4],[2,5],[3,6]])

c = np.array([[[[0], [1], [2], [3]]]])


print(c)

# print((a * (b+c)).sum())

[[[[0]
   [1]
   [2]
   [3]]]]


In [4]:
directions = np.array([
            [-1,0], #UP
            [0,-1], #LEFT
            [1,0], #DOWN
            [0,1] #RIGHT
        ])
print(directions[0])

[-1  0]


In [5]:
obstacles = np.zeros((2, 3))
for i in range(2):
    obstacles[ random.randrange(2) , random.randrange(3)] = 1
print(obstacles)

[[0. 1. 1.]
 [0. 0. 0.]]


In [6]:
c = np.array([[1,4],[2,3]])
print(c.shape)

(2, 2)


In [7]:
c_p = np.array([i for i in range(0,100,5)])/100
c_v = np.array([i for i in range(0,100,10)])/100
c = list(zip(c_p,c_v))

x = c[2][1]
print(c)
print(x)

[(0.0, 0.0), (0.05, 0.1), (0.1, 0.2), (0.15, 0.3), (0.2, 0.4), (0.25, 0.5), (0.3, 0.6), (0.35, 0.7), (0.4, 0.8), (0.45, 0.9)]
0.2


In [8]:
(1-1/6) - 1/6

#1/6 + 1/6 + 1/6 + 1/6 + 1/6

1 - 1/7

x = [random.uniform(0.1,0.9) for _ in range(4)]
print(x)

for i in range(0):
    print(i)

6**2

[0.10698546443684745, 0.8556195972912394, 0.3502540886324085, 0.5975466887016087]


36

In [9]:
states = np.array([(random.random(),random.random()) for i in range(10)])*10
state1 = torch.from_numpy(states[0])
print(state1)
state2 = torch.from_numpy(states[1])
print(state2)
state3 = torch.from_numpy(states[2])

replay = deque(maxlen=2)
replay.append((state1,1,state2,0))
replay.append((state2,1,state2,1))

s1_batch = torch.cat([s1 for(s1,a,s2,r) in replay])
print(s1_batch)

tensor([0.9490, 8.7184], dtype=torch.float64)
tensor([7.2626, 5.1985], dtype=torch.float64)
tensor([0.9490, 8.7184, 7.2626, 5.1985], dtype=torch.float64)


In [13]:
a = [1,2,3,4]
t = torch.tensor(a)
print(t)
m = torch.max(t,-1)[1].item() #index of the max element
print(m)

tensor([1, 2, 3, 4])
3
